### ISSUE TITLE
Обновление пакетов для запуска

### ISSUE THREAD

**Issue by vitalyzhakov** [Demetr26/erth-back#1]
Привет.

Действительно нужно
`composer update` делать для запуска проекта?

Обновление не может сломать проект?

**Comment by Dmitriyshk** [comment]
В репозитории нет vendor, соответственно необходимо инициализировать зависимости.
Нужно выполнить install / update, без этого он вообще не запустится

**Comment by vitalyzhakov** [comment]
Есть принципиальное различие - update обновляет пакеты, а install - устанавливает.
В общем случае использование update приводит к тому, что повторные сборки даже на одной машине будут иметь разные зависимости.

Для расширения кругозора https://youtu.be/Cz6bQw1f23s

**Comment by Dmitriyshk** [comment]
В таком случае и вопрос должен был иначе звучать)

**Comment by Dmitriyshk** [comment]
https://github.com/Demetr26/erth-back/commit/f5f151a68213c49ae1d3cb35fd8ebda58834db91
