### ISSUE TITLE
Подсчёт количества элементов массива VS проверка на пустоту

### ISSUE THREAD

**Issue by vitalyzhakov** [Demetr26/erth-back#2]
https://github.com/Demetr26/erth-back/blob/6162fe999463a92f8a250f714b767ff414d8e23b/modules/api/controllers/ProgrammController.php#L42

https://stackoverflow.com/questions/2216110/checking-for-empty-arrays-count-vs-empty

**Comment by Dmitriyshk** [comment]
Принято к сведению, спасибо

**Comment by Dmitriyshk** [comment]
https://github.com/Demetr26/erth-back/commit/5befddc0ebc786bd3994c01aa5ea8d83c770693f#diff-f76581132995a666f1f19d8f0c8fee12326cfa108eef65d6cdafbd4c5e946424
